"""initial schema

Revision ID: f6949c870ee2
Revises:
Create Date: 2026-08-12 02:49:42.589355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6949c870ee2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institution",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institution")),
    )
    op.create_table(
        "building",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_building_institution_id_institution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building")),
    )
    op.create_table(
        "department",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_department_institution_id_institution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
    )
    op.create_table(
        "feature",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_feature_institution_id_institution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature")),
        sa.UniqueConstraint("institution_id", "name", name=op.f("uq_feature_institution_id")),
    )
    op.create_table(
        "time_grid",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("slots_per_day", sa.Integer(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("day_start_minute", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_time_grid_institution_id_institution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_grid")),
    )
    op.create_table(
        "course",
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_course_department_id_department"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course")),
    )
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_course_code"), ["code"], unique=False)

    op.create_table(
        "instructor",
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("max_slots_per_day", sa.Integer(), nullable=True),
        sa.Column("max_slots_per_week", sa.Integer(), nullable=True),
        sa.Column("max_consecutive_slots", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_instructor_department_id_department"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instructor")),
    )
    with op.batch_alter_table("instructor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instructor_name"), ["name"], unique=False)

    op.create_table(
        "program",
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_program_department_id_department"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program")),
    )
    op.create_table(
        "room",
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.id"],
            name=op.f("fk_room_building_id_building"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
    )
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_room_name"), ["name"], unique=False)

    op.create_table(
        "term",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("time_grid_id", sa.Integer(), nullable=False),
        sa.Column("academic_year", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_term_institution_id_institution"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["time_grid_id"],
            ["time_grid.id"],
            name=op.f("fk_term_time_grid_id_time_grid"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_term")),
    )
    op.create_table(
        "time_grid_break",
        sa.Column("grid_id", sa.Integer(), nullable=False),
        sa.Column("slot_of_day", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["grid_id"],
            ["time_grid.id"],
            name=op.f("fk_time_grid_break_grid_id_time_grid"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_grid_break")),
        sa.UniqueConstraint("grid_id", "slot_of_day", name=op.f("uq_time_grid_break_grid_id")),
    )
    op.create_table(
        "constraint",
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("is_hard", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["term_id"], ["term.id"], name=op.f("fk_constraint_term_id_term"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constraint")),
    )
    with op.batch_alter_table("constraint", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_constraint_term_id"), ["term_id"], unique=False)

    op.create_table(
        "offering",
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_offering_course_id_course"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["term.id"], name=op.f("fk_offering_term_id_term"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offering")),
        sa.UniqueConstraint("term_id", "course_id", name=op.f("uq_offering_term_id")),
    )
    with op.batch_alter_table("offering", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offering_term_id"), ["term_id"], unique=False)

    op.create_table(
        "room_feature",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["feature.id"],
            name=op.f("fk_room_feature_feature_id_feature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], name=op.f("fk_room_feature_room_id_room"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("room_id", "feature_id", name=op.f("pk_room_feature")),
    )
    op.create_table(
        "student_group",
        sa.Column("program_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["student_group.id"],
            name=op.f("fk_student_group_parent_id_student_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
            name=op.f("fk_student_group_program_id_program"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_group")),
    )
    with op.batch_alter_table("student_group", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_student_group_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_student_group_parent_id"), ["parent_id"], unique=False)

    op.create_table(
        "timetable",
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("penalty", sa.Integer(), nullable=True),
        sa.Column("penalty_breakdown", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["timetable.id"],
            name=op.f("fk_timetable_parent_id_timetable"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["term.id"], name=op.f("fk_timetable_term_id_term"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timetable")),
    )
    with op.batch_alter_table("timetable", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_timetable_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_timetable_term_id"), ["term_id"], unique=False)

    op.create_table(
        "unavailability",
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
            name=op.f("fk_unavailability_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unavailability")),
        sa.UniqueConstraint(
            "term_id", "kind", "subject_id", "slot", name=op.f("uq_unavailability_term_id")
        ),
    )
    with op.batch_alter_table("unavailability", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unavailability_term_id"), ["term_id"], unique=False)

    op.create_table(
        "command",
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("before", sa.JSON(), nullable=False),
        sa.Column("after", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("undone_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["timetable_id"],
            ["timetable.id"],
            name=op.f("fk_command_timetable_id_timetable"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_command")),
        sa.UniqueConstraint("timetable_id", "sequence", name=op.f("uq_command_timetable_id")),
    )
    with op.batch_alter_table("command", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_command_timetable_id"), ["timetable_id"], unique=False)

    op.create_table(
        "group_member",
        sa.Column("cohort_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["student_group.id"],
            name=op.f("fk_group_member_cohort_id_student_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["student_group.id"],
            name=op.f("fk_group_member_member_id_student_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cohort_id", "member_id", name=op.f("pk_group_member")),
    )
    op.create_table(
        "session_template",
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("duration_slots", sa.Integer(), nullable=False),
        sa.Column("per_week", sa.Integer(), nullable=False),
        sa.Column("split_per_attendee", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["offering.id"],
            name=op.f("fk_session_template_offering_id_offering"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_template")),
    )
    with op.batch_alter_table("session_template", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_template_offering_id"), ["offering_id"], unique=False
        )

    op.create_table(
        "session",
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("duration_slots", sa.Integer(), nullable=False),
        sa.Column("occurrence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["offering.id"],
            name=op.f("fk_session_offering_id_offering"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_template.id"],
            name=op.f("fk_session_template_id_session_template"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_offering_id"), ["offering_id"], unique=False)

    op.create_table(
        "template_attendee",
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["student_group.id"],
            name=op.f("fk_template_attendee_group_id_student_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_template.id"],
            name=op.f("fk_template_attendee_template_id_session_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("template_id", "group_id", name=op.f("pk_template_attendee")),
    )
    op.create_table(
        "template_feature",
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["feature.id"],
            name=op.f("fk_template_feature_feature_id_feature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_template.id"],
            name=op.f("fk_template_feature_template_id_session_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("template_id", "feature_id", name=op.f("pk_template_feature")),
    )
    op.create_table(
        "template_instructor",
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructor.id"],
            name=op.f("fk_template_instructor_instructor_id_instructor"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_template.id"],
            name=op.f("fk_template_instructor_template_id_session_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "template_id", "instructor_id", name=op.f("pk_template_instructor")
        ),
    )
    op.create_table(
        "assignment",
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("start_slot", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], name=op.f("fk_assignment_room_id_room"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_assignment_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["timetable_id"],
            ["timetable.id"],
            name=op.f("fk_assignment_timetable_id_timetable"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment")),
        sa.UniqueConstraint("timetable_id", "session_id", name=op.f("uq_assignment_timetable_id")),
    )
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assignment_is_pinned"), ["is_pinned"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_assignment_timetable_id"), ["timetable_id"], unique=False
        )

    op.create_table(
        "constraint_target",
        sa.Column("constraint_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constraint_id"],
            ["constraint.id"],
            name=op.f("fk_constraint_target_constraint_id_constraint"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_constraint_target_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("constraint_id", "session_id", name=op.f("pk_constraint_target")),
    )
    op.create_table(
        "session_attendee",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["student_group.id"],
            name=op.f("fk_session_attendee_group_id_student_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_session_attendee_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "group_id", name=op.f("pk_session_attendee")),
    )
    op.create_table(
        "session_feature",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["feature.id"],
            name=op.f("fk_session_feature_feature_id_feature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_session_feature_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "feature_id", name=op.f("pk_session_feature")),
    )
    op.create_table(
        "session_instructor",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructor.id"],
            name=op.f("fk_session_instructor_instructor_id_instructor"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_session_instructor_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", "instructor_id", name=op.f("pk_session_instructor")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_instructor")
    op.drop_table("session_feature")
    op.drop_table("session_attendee")
    op.drop_table("constraint_target")
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignment_timetable_id"))
        batch_op.drop_index(batch_op.f("ix_assignment_is_pinned"))

    op.drop_table("assignment")
    op.drop_table("template_instructor")
    op.drop_table("template_feature")
    op.drop_table("template_attendee")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_offering_id"))

    op.drop_table("session")
    with op.batch_alter_table("session_template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_template_offering_id"))

    op.drop_table("session_template")
    op.drop_table("group_member")
    with op.batch_alter_table("command", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_command_timetable_id"))

    op.drop_table("command")
    with op.batch_alter_table("unavailability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unavailability_term_id"))

    op.drop_table("unavailability")
    with op.batch_alter_table("timetable", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timetable_term_id"))
        batch_op.drop_index(batch_op.f("ix_timetable_status"))

    op.drop_table("timetable")
    with op.batch_alter_table("student_group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_group_parent_id"))
        batch_op.drop_index(batch_op.f("ix_student_group_name"))

    op.drop_table("student_group")
    op.drop_table("room_feature")
    with op.batch_alter_table("offering", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offering_term_id"))

    op.drop_table("offering")
    with op.batch_alter_table("constraint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_constraint_term_id"))

    op.drop_table("constraint")
    op.drop_table("time_grid_break")
    op.drop_table("term")
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_room_name"))

    op.drop_table("room")
    op.drop_table("program")
    with op.batch_alter_table("instructor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instructor_name"))

    op.drop_table("instructor")
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_code"))

    op.drop_table("course")
    op.drop_table("time_grid")
    op.drop_table("feature")
    op.drop_table("department")
    op.drop_table("building")
    op.drop_table("institution")
    # ### end Alembic commands ###
