"""make term names unique within an academic year

Revision ID: 79c594049896
Revises: 1dfde2702d2e
Create Date: 2026-08-13 18:58:31.214279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c594049896'
down_revision: Union[str, Sequence[str], None] = '1dfde2702d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_term_year_name', ['institution_id', 'academic_year', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_constraint('uq_term_year_name', type_='unique')

    # ### end Alembic commands ###
