"""carry counts, week patterns and any-resource constraint targets

Phase 2.7b. Five changes from R5, in one revision.

Four tables change *shape* rather than just gaining a column, and SQLite cannot ALTER a
primary key, so those four are rebuilt explicitly — create, copy, drop, rename — rather
than left to `batch_alter_table`. The autogenerated version of this migration passed on
an empty database and would have silently discarded every existing constraint target,
because it dropped `session_id` without copying it anywhere.

The copy is the point of the whole revision:

    constraint_target(constraint_id, session_id)
        →  constraint_target(constraint_id, target_kind='session', target_id=session_id)

Every row that existed keeps meaning exactly what it meant.

Revision ID: a991295bbdf9
Revises: 79c594049896
Create Date: 2026-08-14 04:44:12.360139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a991295bbdf9'
down_revision: Union[str, Sequence[str], None] = '79c594049896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (table, owner column, owner table) for the three feature links, which differ only in
# which side they hang off.
FEATURE_LINKS = [
    ("room_feature", "room_id", "room"),
    ("template_feature", "template_id", "session_template"),
    ("session_feature", "session_id", "session"),
]


def _rebuild(name: str, *columns, select: str) -> None:
    """Replace a table with a new definition, carrying the rows across.

    `select` names the columns of the *old* table in the order of the new one's, so the
    copy is stated rather than inferred. A rebuild that guesses which columns correspond
    is how data quietly moves into the wrong field.
    """
    op.create_table(f"{name}__new", *columns)
    op.execute(f"INSERT INTO {name}__new {select}")
    op.drop_table(name)
    op.rename_table(f"{name}__new", name)


def upgrade() -> None:
    """Upgrade schema."""
    # -- D3: feature links carry a count -------------------------------------------
    for table, owner, owner_table in FEATURE_LINKS:
        _rebuild(
            table,
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column(owner, sa.Integer(), nullable=False),
            sa.Column("feature_id", sa.Integer(), nullable=False),
            sa.Column("quantity", sa.Integer(), server_default=sa.text("0"), nullable=False),
            sa.ForeignKeyConstraint(
                [owner], [f"{owner_table}.id"],
                name=op.f(f"fk_{table}_{owner}_{owner_table}"), ondelete="CASCADE",
            ),
            sa.ForeignKeyConstraint(
                ["feature_id"], ["feature.id"],
                name=op.f(f"fk_{table}_feature_id_feature"), ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f(f"pk_{table}")),
            sa.UniqueConstraint(owner, "feature_id", name=f"uq_{table}_{owner}"),
            select=f"({owner}, feature_id, quantity) SELECT {owner}, feature_id, 0 FROM {table}",
        )
        op.create_index(op.f(f"ix_{table}_{owner}"), table, [owner], unique=False)
        op.create_index(op.f(f"ix_{table}_feature_id"), table, ["feature_id"], unique=False)

    # -- D1: a constraint can target any resource, not only a session ---------------
    # `target_id` deliberately has no foreign key: no column can point at five tables.
    # The repository checks the reference instead, which is why the check lives in
    # mappers.TARGET_MODELS.
    _rebuild(
        "constraint_target",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("constraint_id", sa.Integer(), nullable=False),
        sa.Column("target_kind", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constraint_id"], ["constraint.id"],
            name=op.f("fk_constraint_target_constraint_id_constraint"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constraint_target")),
        sa.UniqueConstraint(
            "constraint_id", "target_kind", "target_id",
            name="uq_constraint_target_constraint_id",
        ),
        select=(
            "(constraint_id, target_kind, target_id) "
            "SELECT constraint_id, 'session', session_id FROM constraint_target"
        ),
    )
    op.create_index(
        op.f("ix_constraint_target_constraint_id"), "constraint_target", ["constraint_id"]
    )
    op.create_index(op.f("ix_constraint_target_target_kind"), "constraint_target", ["target_kind"])
    op.create_index(op.f("ix_constraint_target_target_id"), "constraint_target", ["target_id"])

    # -- D4, D2, D5: plain additive columns ----------------------------------------
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("turnaround_slots", sa.Integer(), server_default=sa.text("0"), nullable=False)
        )

    for table in ("session", "session_template"):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "week_pattern", sa.String(length=20),
                    server_default=sa.text("'every_week'"), nullable=False,
                )
            )

    with op.batch_alter_table("unavailability", schema=None) as batch_op:
        # Existing rows are hard, which is the only thing they could ever have meant.
        batch_op.add_column(
            sa.Column("is_hard", sa.Boolean(), server_default=sa.text("1"), nullable=False)
        )
        batch_op.add_column(
            sa.Column("weight", sa.Integer(), server_default=sa.text("1"), nullable=False)
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("unavailability", schema=None) as batch_op:
        batch_op.drop_column("weight")
        batch_op.drop_column("is_hard")

    for table in ("session_template", "session"):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.drop_column("week_pattern")

    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.drop_column("turnaround_slots")

    # Targets naming anything other than a session cannot be represented by the old
    # schema, so they are dropped rather than mangled into a session id that would point
    # at an unrelated row. Losing them is the honest outcome of going back.
    _rebuild(
        "constraint_target",
        sa.Column("constraint_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constraint_id"], ["constraint.id"],
            name=op.f("fk_constraint_target_constraint_id_constraint"), ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"],
            name=op.f("fk_constraint_target_session_id_session"), ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("constraint_id", "session_id", name=op.f("pk_constraint_target")),
        select=(
            "(constraint_id, session_id) SELECT constraint_id, target_id "
            "FROM constraint_target WHERE target_kind = 'session'"
        ),
    )

    for table, owner, owner_table in FEATURE_LINKS:
        _rebuild(
            table,
            sa.Column(owner, sa.Integer(), nullable=False),
            sa.Column("feature_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                [owner], [f"{owner_table}.id"],
                name=op.f(f"fk_{table}_{owner}_{owner_table}"), ondelete="CASCADE",
            ),
            sa.ForeignKeyConstraint(
                ["feature_id"], ["feature.id"],
                name=op.f(f"fk_{table}_feature_id_feature"), ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint(owner, "feature_id", name=op.f(f"pk_{table}")),
            select=f"({owner}, feature_id) SELECT {owner}, feature_id FROM {table}",
        )
