"""scope name uniqueness for structural entities

Revision ID: f287ffef4a9f
Revises: 6a6ec16bba7d
Create Date: 2026-08-13 01:46:08.482836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f287ffef4a9f'
down_revision: Union[str, Sequence[str], None] = '6a6ec16bba7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_building_institution_name', ['institution_id', 'name'])

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_department_institution_name', ['institution_id', 'name'])

    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_institution_name', ['name'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_room_building_name', ['building_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('uq_room_building_name', type_='unique')

    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.drop_constraint('uq_institution_name', type_='unique')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint('uq_department_institution_name', type_='unique')

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_constraint('uq_building_institution_name', type_='unique')

    # ### end Alembic commands ###
