"""make course codes unique within a department

Revision ID: 1dfde2702d2e
Revises: f287ffef4a9f
Create Date: 2026-08-13 14:00:44.372011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfde2702d2e'
down_revision: Union[str, Sequence[str], None] = 'f287ffef4a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_course_department_code', ['department_id', 'code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_department_code', type_='unique')

    # ### end Alembic commands ###
