"""The shape of the report, built offline from the two vendored instances.

`test_report.py` checks the *committed* report against all 36 and needs the download. This
checks that the document is built correctly at all, which is the part somebody editing the
prose needs fast feedback on — and the part where a section can silently stop being rendered.

Two instances make a small report and every section still has to appear in it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tessera.importers.itc import Instance, read
from tessera.importers.itc.apply import Fate, mapped
from tessera.importers.itc.fidelity import Reading, report

FIXTURES = Path(__file__).parent / "fixtures"


def _reading(name: str, band: str) -> Reading:
    instance: Instance = read(FIXTURES / f"{name}.xml")
    return Reading(band=band, instance=instance, plan=mapped(instance))


@pytest.fixture(scope="module")
def readings() -> list[Reading]:
    return [_reading("bet-sum18", "Test"), _reading("pu-cs-fal07", "Test")]


@pytest.fixture(scope="module")
def text(readings: list[Reading]) -> str:
    return report(readings)


class TestTheDocument:
    def test_every_section_is_present(self, text: str) -> None:
        for heading in (
            "# Tessera against ITC-2019",
            "## The short version",
            "## The two sets are kept apart",
            "## Every instance",
            "## Carried",
            "## Approximated",
            "## Dropped",
            "## The distribution constraints",
            "## What this says about Tessera",
            "## Reproducing this",
        ):
            assert heading in text, f"{heading!r} is missing from the report"

    def test_every_instance_gets_a_row(self, text: str, readings: list[Reading]) -> None:
        for reading in readings:
            assert f"| `{reading.name}` |" in text

    def test_it_states_the_teaching_week_each_one_got(self, text: str) -> None:
        """The grid is per instance, so the table has to say which one each got — otherwise
        a reader comparing two rows cannot tell why one lost more than the other."""
        assert "53 slots of 10 min from 08:00" in text
        assert "62 slots of 10 min from 07:30" in text

    def test_it_carries_no_generation_date(self, text: str) -> None:
        """Deliberate. A date makes every regeneration a diff and turns the staleness guard
        in `test_report.py` into noise that people learn to ignore."""
        assert "Generated by `tessera fidelity`" in text
        assert "2026" not in text


class TestItDoesNotFlatter:
    def test_it_reports_no_lossless_import(self, text: str) -> None:
        assert "0 of the 2 instances import without loss" in text

    def test_no_time_option_appears_as_carried(self, text: str, readings: list[Reading]) -> None:
        """The correction this report needed. Time options landing on the grid unchanged
        were counted as carried, which put over a million things in that column across the
        set — none of them in any project, because their classes are dropped."""
        carried = text[text.index("## Carried") : text.index("## Approximated")]

        assert "class time options" not in carried
        for reading in readings:
            assert "class time options" in _section(text, "## Dropped")
            assert reading.plan.fit.total == sum(len(k.times) for k in reading.instance.classes)

    def test_the_grid_measurement_says_what_it_is_not(self, text: str) -> None:
        """It is a property of the grid, not an arrival. The sentence saying so is the
        difference between a useful number and a misleading one."""
        assert "not a column in the tables above" in text
        assert "if classes ever became representable" in text

    def test_every_dropped_thing_is_named_with_a_count(
        self, text: str, readings: list[Reading]
    ) -> None:
        dropped = {
            entry.what for reading in readings for entry in reading.plan.ledger.of(Fate.DROPPED)
        }

        for what in dropped:
            assert what.removeprefix("distribution: ") in text

    def test_a_type_with_a_counterpart_is_still_listed_as_dropped(self, text: str) -> None:
        """`NotOverlap` maps to `NOT_OVERLAP` and is dropped anyway, because it names classes
        that were dropped. Listing only the types with no counterpart would understate it."""
        assert "`NOT_OVERLAP`" in text
        assert "They are dropped too" in text

    def test_the_most_used_type_is_named_in_the_prose(self, text: str) -> None:
        """Not left to a reader to spot in a table. It is the report's most uncomfortable
        finding and D7 exists to stop it being smoothed away."""
        assert "`SameAttendees`" in text
        assert "no counterpart in Tessera" in text


def _section(text: str, heading: str) -> str:
    start = text.index(heading)
    rest = text[start + len(heading) :]
    end = rest.find("\n## ")
    return rest if end == -1 else rest[:end]
