"""What Tessera makes of the ITC-2007 instances, per instance.

4.0's report answered *what does the model lose*. This one answers a sharper question, because
CB-CTT crosses almost intact: **does a timetable still exist once Tessera's rules apply?**

The interesting rule is room capacity. CB-CTT treats it as a soft cost — overfill a room and
pay a point per student — and its instances were built by people who could do that. Tessera
treats it as an invariant: *"capacity is a fact about the building, not a cost to weigh against
convenience."* That is a defensible difference and it is not free, and this report is where the
bill arrives.

**No solving is needed to find the worst of it.** If more lectures need a large room than there
are large-room periods in the week, no arrangement can work — pigeonhole, checkable by
arithmetic, and *proof* rather than a solver giving up. The one instance that fails this way
fails it by four.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from tessera.importers.cbctt.apply import Mapped, mapped
from tessera.importers.cbctt.format import Instance, read


@dataclass(frozen=True, slots=True)
class Bottleneck:
    """A proof that no timetable exists, found by counting rather than searching."""

    seats: int
    """The room size at which demand outruns supply."""

    lectures: int
    """Lectures needing a room at least that big."""

    room_slots: int
    """Room-periods in the week that are at least that big."""

    @property
    def short_by(self) -> int:
        return self.lectures - self.room_slots


def bottleneck(instance: Instance) -> Bottleneck | None:
    """The worst capacity shortfall, if there is one.

    For each distinct course size, count the lectures needing a room that big and the
    room-periods that big. Demand above supply cannot be arranged, however clever the solver.

    Cheap — a few hundred comparisons — and it turns "the solver ran out of time" into "there
    is no answer", which are different sentences and only one of them is a reason to change
    the data. #205 keeps those apart in the solver; this is what lets the report say which.
    """
    periods = instance.days * instance.periods_per_day
    worst: Bottleneck | None = None

    for seats in sorted({course.students for course in instance.courses}):
        lectures = sum(c.lectures for c in instance.courses if c.students >= seats)
        room_slots = sum(1 for r in instance.rooms if r.capacity >= seats) * periods
        if lectures > room_slots and (worst is None or lectures - room_slots > worst.short_by):
            worst = Bottleneck(seats=seats, lectures=lectures, room_slots=room_slots)
    return worst


@dataclass(frozen=True)
class Reading:
    """One instance: what it holds, what it became, and whether it can be timetabled."""

    stem: str
    instance: Instance
    term: Mapped
    blocked: Bottleneck | None
    outcome: str
    """What a solve returned. Recorded rather than recomputed — twenty-one solves take
    minutes, and the report is read far more often than it is regenerated."""

    seconds: float


def gather(directory: Path, outcomes: dict[str, tuple[str, float]]) -> list[Reading]:
    """Read and map every instance, pairing each with a recorded solve outcome."""
    found = []
    for path in sorted(directory.glob("comp*.ctt")):
        instance = read(path)
        outcome, seconds = outcomes.get(path.stem, ("not run", 0.0))
        found.append(
            Reading(
                stem=path.stem,
                instance=instance,
                term=mapped(instance),
                blocked=bottleneck(instance),
                outcome=outcome,
                seconds=seconds,
            )
        )
    return found


def report(readings: list[Reading]) -> str:
    return "\n".join(
        [*_opening(readings), *_per_instance(readings), *_capacity(readings), *_closing(readings)]
    )


def _opening(readings: list[Reading]) -> list[str]:
    solved = [r for r in readings if r.outcome == "solved"]
    impossible = [r for r in readings if r.blocked]
    return [
        "# Tessera against ITC-2007",
        "",
        "What Tessera's model makes of the 21 curriculum-based course timetabling instances "
        "from the second International Timetabling Competition — real timetables from the "
        "University of Udine.",
        "",
        "Generated by `tessera fidelity --suite cbctt` from the same code that performs the "
        "import, against the instances pinned in "
        "[`scripts/itc2007-instances.sha256`](../../scripts/itc2007-instances.sha256).",
        "",
        "## The short version",
        "",
        f"**{len(solved)} of the {len(readings)} instances are solved**, and every solution is "
        "confirmed feasible and complete by the validator, which shares none of the solver's "
        "logic.",
        "",
        "**The teaching structure crosses intact.** That is worth stating next to the ITC-2019 "
        "report, which had to drop all 52,254 of its classes: a Tessera session must be taught "
        "to a student group, and those instances state individual student enrolments with no "
        "programme tree to hang one on. **A CB-CTT curriculum is a cohort**, so the barrier is "
        "simply absent here. Courses, lectures, teachers, curricula, rooms and the week all "
        "map with nothing lost.",
        "",
        "What does not map is small and named: the four soft constraints a CB-CTT solution is "
        "*scored* on — this phase places lectures and weighs nothing — and course-level "
        "unavailability where the teacher teaches more than one course, which cannot be "
        "carried without forbidding their other courses too.",
        "",
        f"**And one rule costs more than the rest combined.** {len(impossible)} instance"
        f"{' is' if len(impossible) == 1 else 's are'} **provably impossible** under Tessera "
        "— not unsolved, impossible. See below.",
        "",
    ]


def _per_instance(readings: list[Reading]) -> list[str]:
    lines = [
        "## Every instance",
        "",
        "| instance | name | lectures | rooms | week | outcome |",
        "|---|---|---:|---:|---:|---|",
    ]
    for r in readings:
        i = r.instance
        verdict = (
            "**impossible** (see below)"
            if r.blocked
            else f"solved in {r.seconds:.0f}s"
            if r.outcome == "solved"
            else "not found in 300s"
        )
        lines.append(
            f"| `{r.stem}` | {i.name} | {i.lectures} | {len(i.rooms)} | "
            f"{i.days} days x {i.periods_per_day} | {verdict} |"
        )
    return [*lines, ""]


def _capacity(readings: list[Reading]) -> list[str]:
    blocked = [r for r in readings if r.blocked]
    lines = [
        "## Where Tessera is stricter than the competition",
        "",
        "CB-CTT scores room capacity as a **soft** cost: put eighty students in a room for "
        "sixty and pay twenty points. Tessera makes it an invariant — *capacity is a fact "
        "about the building, not a cost to weigh against convenience* — so the same placement "
        "is refused outright.",
        "",
        "The instances were built by people for whom overfilling was legal. So this is not a "
        "difference of opinion about a benchmark; it is the difference between two models, and "
        "here is what it costs:",
        "",
    ]
    for r in blocked:
        assert r.blocked is not None
        b = r.blocked
        lines += [
            f"### `{r.stem}` cannot be timetabled at all",
            "",
            f"**{b.lectures} lectures need a room seating at least {b.seats}, and the whole "
            f"week contains {b.room_slots} such room-periods.** Short by {b.short_by}.",
            "",
            "That is a proof, not a solver giving up: no arrangement of anything can put "
            f"{b.lectures} lectures into {b.room_slots} places. The competition's own "
            "documentation states every ITC-2007 instance has at least one feasible solution — "
            "and it does, *under CB-CTT's rules*, where the overflow is paid for rather than "
            "forbidden.",
            "",
        ]

    unsolved = [r for r in readings if r.outcome != "solved" and not r.blocked]
    if unsolved:
        lines += [
            "### And one more that capacity makes hard without making impossible",
            "",
        ]
        for r in unsolved:
            lines.append(
                f"**`{r.stem}`** was not solved in 300 seconds. No counting argument proves it "
                "impossible, and with capacity relaxed to CB-CTT's soft reading the same "
                "instance solves — so the hard rule is implicated, but this one may simply be "
                "a search problem rather than an arithmetic one. 4.4 is where that is "
                "addressed."
            )
            lines.append("")
    return lines


def _closing(readings: list[Reading]) -> list[str]:
    dropped: dict[str, int] = {}
    for r in readings:
        for entry in r.term.dropped:
            dropped[entry.what] = dropped.get(entry.what, 0) + entry.count
    return [
        "## What the mapping drops",
        "",
        "| | across all instances | |",
        "|---|---:|---|",
        *(
            f"| {what} | {count:,} | {_why(readings, what)} |"
            for what, count in sorted(dropped.items(), key=lambda kv: -kv[1])
        ),
        "",
        "## What this says about Tessera",
        "",
        "**Hard capacity is a real position with a real cost.** It is defensible — a room that "
        "seats sixty seats sixty, and a timetable that pretends otherwise is one somebody "
        "discovers at the door. It also means Tessera would refuse a timetable a real "
        "university ran, because `comp01` is a real timetable that Udine ran. Both of those "
        "are true and the second is not a reason to abandon the first; it is a reason to say "
        "so where a reader can see it.",
        "",
        "**The competition's guarantee does not transfer, and that is the useful finding.** "
        "*Every ITC-2007 instance has at least one feasible solution* is true of CB-CTT and "
        "false of Tessera, by four lectures, on one instance out of twenty-one.",
        "",
        "## Reproducing this",
        "",
        "```bash",
        "tessera fidelity --suite cbctt --instances /path/to/ITC-2007",
        "```",
        "",
        "The instances are served openly by the competition's own site; "
        "`scripts/itc2007-instances.sha256` records the SHA-256 of all 21, so a re-issued or "
        "corrupted file is caught rather than silently parsed.",
    ]


def _why(readings: list[Reading], what: str) -> str:
    for r in readings:
        for entry in r.term.dropped:
            if entry.what == what:
                return entry.because
    return ""
