"""The fidelity report: what Tessera carried, approximated and dropped, per instance.

D1 replaced *"all 30 instances parse without loss"* with this, because ITC models things
Tessera deliberately does not and "without loss" was unfalsifiable. What replaces it is a
claim a reader can check: **every entity Tessera claims to model is carried, and everything
else is named with a count.**

**Generated, never written by hand.** A report typed out once is accurate once; this one is
produced from the same ledgers the importer builds, so it cannot describe a mapping other than
the one that runs. `tests/importers/itc/test_report.py` regenerates it and compares against
the committed copy, which is what makes the file in `docs/` evidence rather than prose.

**No date, deliberately.** A generated-on line would make every regeneration a diff and turn
the guard above into noise; the instances are pinned by `scripts/itc-instances.sha256`
instead, which is the thing that actually needs to be the same.

The report is allowed to come out badly. That is the point of D1 — and it does come out badly,
which is worth more than a report that flattered the model would have been.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from tessera.importers.itc.apply import COUNTERPARTS, Fate, Mapped, mapped
from tessera.importers.itc.format import Instance, read

#: The competition bands, in the order the organisers published them. `Test` last because
#: D8 turns on keeping it distinct: published results are comparable against the 30, while
#: the 6 are what the reference solvers are usually demonstrated on.
BANDS = ("Early", "Middle", "Late", "Test")

COMPETITION = BANDS[:3]


@dataclass(frozen=True)
class Reading:
    """One instance, as read and as mapped."""

    band: str
    instance: Instance
    plan: Mapped

    @property
    def name(self) -> str:
        return self.instance.name

    @property
    def is_competition(self) -> bool:
        return self.band in COMPETITION


def gather(instances: Path) -> list[Reading]:
    """Read and map every instance under the extracted `Instances` directory."""
    found = []
    for band in BANDS:
        for path in sorted((instances / band).glob("*.xml")):
            instance = read(path)
            found.append(Reading(band=band, instance=instance, plan=mapped(instance)))
    return found


def report(readings: list[Reading]) -> str:
    """The whole document."""
    return "\n".join(
        [
            *_opening(readings),
            *_per_instance(readings),
            *_carried(readings),
            *_approximated(readings),
            *_dropped(readings),
            *_distributions(readings),
            *_conclusion(readings),
        ]
    )


def _opening(readings: list[Reading]) -> list[str]:
    lossless = [r.name for r in readings if r.plan.ledger.is_lossless]
    competition = [r for r in readings if r.is_competition]
    return [
        "# Tessera against ITC-2019",
        "",
        "What Tessera's data model can hold of the International Timetabling Competition 2019",
        "instances, and what it cannot.",
        "",
        "Generated by `tessera fidelity` from the same code that performs the import, against "
        f"the {len(readings)} instances pinned in "
        "[`scripts/itc-instances.sha256`](../../scripts/itc-instances.sha256). It is "
        "regenerated and compared in the test suite, so it describes the importer that exists "
        "rather than one that once did.",
        "",
        "## The short version",
        "",
        f"**{len(lossless)} of the {len(readings)} instances import without loss.**"
        + ("" if lossless else " None of them."),
        "",
        "That is the honest headline and it is not a near miss. An ITC instance is mostly a "
        "*scheduling problem* — per-class time domains, ranked room lists, penalties on every "
        "alternative — and Tessera holds a *university*. What survives the crossing is the "
        "university part: rooms, courses, offerings, a teaching week, and when rooms are "
        "closed. What does not is the part a solver would consume.",
        "",
        "The single reason for most of it is one sentence long. A Tessera session template "
        "must be taught to at least one student group; a cohort must name the structural "
        "groups it draws from; ITC states individual student enrolments and has no programme "
        "tree. So every class in every instance is dropped, and every distribution constraint "
        "with them — including the six types that **do** have a counterpart, because they "
        "would refer to classes that no longer exist.",
        "",
        "Carrying them would mean inventing a programme tree the instances do not state, and "
        "then reporting a fidelity the invention created. That was ruled out before these "
        "numbers were known, which is the only time such a rule can be set honestly.",
        "",
        "## The two sets are kept apart",
        "",
        f"**{len(competition)} competition instances** (Early, Middle, Late) and "
        f"**{len(readings) - len(competition)} test instances**. Published results are "
        "comparable against the competition set; the test set is what the reference solvers "
        "are usually demonstrated on. Conflating them would make a benchmark claim that "
        "cannot be checked against the literature.",
        "",
    ]


def _per_instance(readings: list[Reading]) -> list[str]:
    lines = [
        "## Every instance",
        "",
        "`carried`, `approximated` and `dropped` count *things* — a room, a course, one time "
        "option, one distribution constraint — so they are comparable within a row and not "
        "across instances of different sizes.",
        "",
        "| instance | band | teaching week | carried | approximated | dropped |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for r in readings:
        grid = r.plan.grid
        start = f"{grid.day_start_minute // 60:02d}:{grid.day_start_minute % 60:02d}"
        lines.append(
            f"| `{r.name}` | {r.band} | "
            f"{grid.slots_per_day} slots of {grid.slot_minutes} min from {start} | "
            f"{r.plan.ledger.total(Fate.CARRIED):,} | "
            f"{r.plan.ledger.total(Fate.APPROXIMATED):,} | "
            f"{r.plan.ledger.total(Fate.DROPPED):,} |"
        )
    return [*lines, ""]


def _carried(readings: list[Reading]) -> list[str]:
    totals = _totals(readings, Fate.CARRIED)
    return [
        "## Carried",
        "",
        "Held exactly. Reading these back out of a project gives the same answer the file gave.",
        "",
        *_table(totals),
        "",
        "Rooms keep their capacities and courses their identity; each course becomes an "
        "offering in the instance's term, so the catalogue is not left unoffered. Each "
        "instance lands as **its own institution**: two instances both name a room `Room 1` "
        "and mean different rooms, and merging them would produce a project that looks fine "
        "and describes nowhere.",
        "",
    ]


def _approximated(readings: list[Reading]) -> list[str]:
    totals = _totals(readings, Fate.APPROXIMATED)
    granularity = Counter(r.plan.grid.slot_minutes for r in readings)
    exact_grids = sum(1 for r in readings if r.plan.grid.is_exact)
    landed = sum(r.plan.fit.exact for r in readings)
    times = sum(r.plan.fit.total for r in readings)
    return [
        "## Approximated",
        "",
        "Held, but changed.",
        "",
        *(
            _table(totals)
            if totals
            else [
                "Almost nothing, and not because the import is faithful — because so little "
                "is carried that there is little left to approximate. Only room closures "
                "reach the project on a grid coarser than the one they were written on."
            ]
        ),
        "",
        "### The teaching grid",
        "",
        "ITC states every time to **five minutes** across a 288-slot day. Tessera's "
        "`TimeGrid` allows at most 96 slots in a day, and that ceiling is not moved for a "
        "benchmark — a data model reshaped to fit a competition is optimised for the "
        "competition.",
        "",
        "So each instance gets the finest grid that fits, over the hours it actually teaches "
        "rather than ITC's midnight-to-midnight day:",
        "",
        "| slot length | instances |",
        "|---|---:|",
        *(f"| {minutes} minutes | {count} |" for minutes, count in sorted(granularity.items())),
        "",
        f"**{exact_grids} instances keep five-minute resolution.** A single grid for all of "
        "them would have to be 15 minutes, so choosing per instance is what keeps "
        f"{granularity.get(10, 0)} of them at 10.",
        "",
        "### How well the grid would have held the class times",
        "",
        f"**{landed:,} of {times:,} class time options ({landed * 100 // times}%) land on "
        "their instance's grid unchanged.**",
        "",
        "This is a measurement, not a column in the tables above, and the distinction "
        "matters. Every class is dropped, so not one of these time options is in a project "
        "anywhere — counting them as *carried* would put a million things in the carried "
        "column that a reader could not find if they went looking. What the number says is "
        "narrower and still worth knowing: **if classes ever became representable, the "
        "teaching week is not what would stop them.**",
        "",
        "Class times round **outward**, never inward. Rounding a 50-minute class down would "
        "hand the solver a room for the last five minutes of a class still in it, and the "
        "resulting timetable would be wrong while remaining perfectly consistent with the "
        "data it was given.",
        "",
    ]


def _dropped(readings: list[Reading]) -> list[str]:
    totals = _totals(readings, Fate.DROPPED, exclude_prefix="distribution: ")
    return [
        "## Dropped",
        "",
        "Not held at all — named with a count rather than silently absent. Distribution "
        "constraints have their own section below.",
        "",
        *_table(totals),
        "",
        "### Room closures are dropped rather than widened",
        "",
        "ITC closes a room in named weeks; Tessera blocks a slot or does not. Widening a "
        "part-term closure to the whole term would block a room in weeks the instance says "
        "it is free — **not a lossy import but a wrong one**, and the kind of wrongness that "
        "produces a plausible timetable nobody can falsify. The mirror case is not counted "
        "as loss at all: a closure lying entirely outside the teaching day forbids nothing, "
        "because nothing can be scheduled there to forbid.",
        "",
    ]


def _distributions(readings: list[Reading]) -> list[str]:
    counted: Counter[str] = Counter()
    instances: Counter[str] = Counter()
    for reading in readings:
        names = Counter(d.name for d in reading.instance.distributions)
        counted.update(names)
        instances.update(names.keys())

    lines = [
        "## The distribution constraints, weighted by how much the benchmark uses them",
        "",
        "Comparing the 19 ITC types against Tessera's 16 kinds *by name* overstates the "
        "overlap and understates what the overlap is worth. Weighted by occurrences, the "
        "picture is different — and the headline is uncomfortable:",
        "",
        "| ITC type | occurrences | in instances | Tessera's counterpart |",
        "|---|---:|---:|---|",
    ]
    for name, count in counted.most_common():
        counterpart = COUNTERPARTS.get(name)
        lines.append(
            f"| `{name}` | {count:,} | {instances[name]}/{len(readings)} | "
            f"{'`' + counterpart.name + '`' if counterpart else '**none**'} |"
        )

    top, top_count = counted.most_common(1)[0]
    return [
        *lines,
        "",
        f"**The most-used constraint type in the whole benchmark has no counterpart in "
        f"Tessera, and it appears in {instances[top]} of the {len(readings)} instances.** "
        f"`{top}` occurs {top_count:,} times.",
        "",
        f"`{top}` means *these classes share students, so they must not collide and must "
        "allow time to travel between them*. In Tessera that is **implied** by student "
        "groups rather than stated as a constraint: two sessions taught to the same group "
        "cannot overlap, and nobody writes a rule to say so. Whether that is a genuine gap "
        "or a modelling difference is not something this report can settle — what it can do "
        "is refuse to hide the number.",
        "",
        "Synthesising groups from it would make the figures above look considerably better "
        "and mean nothing, because the fidelity would be against structure this importer "
        "invented rather than structure the instance stated.",
        "",
        "Every type is listed, including those with a counterpart. **They are dropped too**, "
        "and not because of the constraint: each one names classes, and no class is carried. "
        "A `SameRoom` over two classes that do not exist is not a constraint, and writing it "
        "as one would be this report flattering itself.",
        "",
    ]


def _conclusion(readings: list[Reading]) -> list[str]:
    weeks = sum(1 for r in readings if r.instance.needs_multiple_weeks)
    return [
        "## What this says about Tessera",
        "",
        "Three findings, in the order they are worth acting on.",
        "",
        f"**1. Partial-week teaching is normal.** {weeks} of the {len(readings)} instances "
        "have classes that run in some weeks and not others — AGH, Masaryk, Purdue, "
        "Bethlehem, Marymount. These are real universities, not a competition artefact. "
        "Tessera offers every week, odd weeks or even weeks; the instances carry arbitrary "
        "masks like *first half of term* and *one week only*. This is the strongest "
        "candidate for a genuine gap in the data model.",
        "",
        "**2. A session must be taught to somebody.** Requiring a student group is, on its "
        "own, what drops every class in every instance. It is a sound rule for a university "
        "product — a lecture with no audience is a data-entry mistake — and an absolute "
        "barrier to a competition instance. Both are true at once, and the barrier is "
        "structural rather than a missing field: ITC has no programme tree to hang a group "
        "on, so there is nothing to map from.",
        "",
        "**3. Per-class time and room domains have no home.** ITC gives every class an "
        "explicit ranked list of times and rooms with penalties; Tessera derives what is "
        "eligible from capacity, features and rules. That is a real difference in kind, not "
        "a missing field.",
        "",
        "None of the three is fixed here. Reshaping the data model in the phase that "
        "discovered the mismatch would optimise it for a benchmark, and each of these is now "
        "a backlog entry naming the instances that prove it — which is more than the model "
        "had before this was measured.",
        "",
        "## Reproducing this",
        "",
        "```bash",
        "tessera fidelity --instances /path/to/Instances --out docs/fidelity/itc-2019.md",
        "```",
        "",
        "The instances are not redistributed; registration at [itc2019.org]"
        "(https://www.itc2019.org/) is required. Verify a download against "
        "`scripts/itc-instances.sha256` first — every number above is attached to those "
        "exact bytes.",
    ]


def _totals(
    readings: list[Reading], fate: Fate, *, exclude_prefix: str = ""
) -> list[tuple[str, int, str]]:
    """Every ledger line of one fate, summed across instances, largest first.

    The reason travels with the count. A table of bare numbers would say what was lost and
    leave the reader to guess why, which for the large ones is exactly the question.
    """
    counts: Counter[str] = Counter()
    because: dict[str, str] = {}
    for reading in readings:
        for entry in reading.plan.ledger.of(fate):
            if exclude_prefix and entry.what.startswith(exclude_prefix):
                continue
            counts[entry.what] += entry.count
            if entry.because and entry.what not in because:
                because[entry.what] = entry.because
    return [(what, count, because.get(what, "")) for what, count in counts.most_common()]


def _table(totals: list[tuple[str, int, str]]) -> list[str]:
    return [
        "| | across all instances | |",
        "|---|---:|---|",
        *(f"| {what} | {count:,} | {reason} |" for what, count, reason in totals),
    ]
